"""
Generates the downloadable PDF report using WeasyPrint (HTML/CSS -> PDF).
Styling mirrors the sample PDF: amber header bar, clean section labels,
competitor table.
"""
import base64
from io import BytesIO
from typing import List
from weasyprint import HTML

from models.schemas import CompanyInfo, Competitor

REPORT_CSS = """
@page { size: A4; margin: 28mm 18mm; }
body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a1a; }
.header-bar { border-top: 5px solid #f5a623; padding-top: 10px; margin-bottom: 18px; }
.eyebrow { color: #f5a623; font-size: 11px; letter-spacing: 1.5px; text-transform: uppercase; font-weight: 700; }
h1 { font-size: 26px; margin: 4px 0 0 0; }
.section { margin-top: 22px; }
.section-title { font-size: 12px; letter-spacing: 1px; text-transform: uppercase; color: #f5a623; font-weight: 700; border-bottom: 1px solid #eee; padding-bottom: 4px; margin-bottom: 10px; }
.info-grid { display: flex; flex-wrap: wrap; gap: 24px; }
.info-item { min-width: 200px; }
.info-label { font-size: 10px; text-transform: uppercase; color: #888; margin-bottom: 2px; }
.info-value { font-size: 13px; }
ul { margin: 0; padding-left: 18px; }
li { margin-bottom: 6px; font-size: 13px; line-height: 1.5; }
table { width: 100%; border-collapse: collapse; margin-top: 6px; }
th, td { text-align: left; padding: 8px 6px; font-size: 12px; border-bottom: 1px solid #eee; }
th { color: #888; text-transform: uppercase; font-size: 10px; }
.footer { margin-top: 30px; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 8px; }
"""


def _company_info_html(company: CompanyInfo) -> str:
    return f"""
    <div class="section-title">Company Information</div>
    <div class="info-grid">
      <div class="info-item"><div class="info-label">Website</div>
        <div class="info-value">{company.website or "Not publicly listed"}</div></div>
      <div class="info-item"><div class="info-label">Phone</div>
        <div class="info-value">{company.phone or "Not publicly listed"}</div></div>
      <div class="info-item"><div class="info-label">Address</div>
        <div class="info-value">{company.address or "Not publicly listed"}</div></div>
    </div>
    """


def _list_section(title: str, items: List[str]) -> str:
    lis = "".join(f"<li>{i}</li>" for i in items) or "<li>Not available</li>"
    return f'<div class="section"><div class="section-title">{title}</div><ul>{lis}</ul></div>'


def _competitors_html(competitors: List[Competitor]) -> str:
    rows = "".join(
        f"<tr><td>{c.name}</td><td>{c.website or '—'}</td></tr>" for c in competitors
    ) or "<tr><td colspan='2'>No competitors identified</td></tr>"
    return f"""
    <div class="section">
      <div class="section-title">Competitors</div>
      <table>
        <thead><tr><th>Company</th><th>Website</th></tr></thead>
        <tbody>{rows}</tbody>
      </table>
    </div>
    """


def build_report_html(company: CompanyInfo, competitors: List[Competitor]) -> str:
    return f"""
    <html><head><style>{REPORT_CSS}</style></head>
    <body>
      <div class="header-bar">
        <div class="eyebrow">Relu Consultancy · Company Research Report</div>
        <h1>{company.name}</h1>
      </div>
      {_company_info_html(company)}
      {_list_section("Products &amp; Services", company.products_services)}
      {_list_section("AI-Generated Pain Points", company.pain_points)}
      {_competitors_html(competitors)}
      <div class="footer">Generated by the Relu Company Research Assistant.</div>
    </body></html>
    """


def generate_pdf_base64(company: CompanyInfo, competitors: List[Competitor]) -> str:
    html_str = build_report_html(company, competitors)
    buffer = BytesIO()
    HTML(string=html_str).write_pdf(buffer)
    return base64.b64encode(buffer.getvalue()).decode("utf-8")
